export const SET_LOGIN = 'SET_LOGIN'
export const SET_LOGOUT = 'SET_LOGOUT'
export const SET_STATUS = 'SET_STATUS'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_CURRENTAUDIO = 'SET_CURRENTAUDIO'
